"""Skalar capital-mechanics engine.

Domain models, per-cohort deal parameters, collections, and (later phases) cash events.
Depends only on ``skalar_data_access``.
"""

from __future__ import annotations

from .cash_events import (
    DEFAULT_LEVERAGE,
    CashEvent,
    GCDates,
    NettingInstruction,
    TransactedLedgerRow,
    build_downstream_cash_events,
    build_netting,
    build_transacted_ledger,
    derive_debt_taken,
    sharing_events_from_schedule,
)
from .collections import (
    CohortIndex,
    CollectionsCell,
    CollectionsMatrix,
    CollectionsMeta,
    build_collections,
    cohort_index,
)
from .defaults import DefaultRegime, load_defaults
from .errors import CapitalMechanicsError, ResolutionError
from .income import (
    ComplianceReport,
    ComplianceViolation,
    ComplianceViolationKind,
    FlatMultiplePricing,
    FundingRequest,
    IncrementalMechanic,
    LinearLadderMechanic,
    MoicLadderPricing,
    ReferenceIncomeCell,
    ReferenceIncomeSeries,
    SharingCell,
    SharingSchedule,
    ThresholdCheck,
    ThresholdRequirementResult,
    ThresholdResult,
    WindDownAssessment,
    check_compliance,
    evaluate_threshold,
    moic_from_ladder,
    payback_age,
    reference_income,
    return_cap,
    sharing_schedule,
    winddown_payment,
)
from .models import (
    CashEventKind,
    Company,
    DayCount,
    DealParameters,
    FundingBand,
    LeverageStructure,
    MoicLadder,
    Money,
    Pct,
    PerPeriodCap,
    PricingStrategyKind,
    SettlementWindows,
    SharingBand,
    ThresholdBasis,
    ThresholdExit,
    ThresholdMechanic,
    ThresholdSpec,
    ThresholdTiming,
    WindDownSpec,
)
from .resolve import load_company, resolve_deal_parameters

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_LEVERAGE",
    "CapitalMechanicsError",
    "CashEvent",
    "CashEventKind",
    "CohortIndex",
    "CollectionsCell",
    "CollectionsMatrix",
    "CollectionsMeta",
    "Company",
    "ComplianceReport",
    "ComplianceViolation",
    "ComplianceViolationKind",
    "DayCount",
    "DealParameters",
    "DefaultRegime",
    "FlatMultiplePricing",
    "FundingBand",
    "FundingRequest",
    "GCDates",
    "IncrementalMechanic",
    "LeverageStructure",
    "LinearLadderMechanic",
    "MoicLadder",
    "MoicLadderPricing",
    "Money",
    "NettingInstruction",
    "Pct",
    "PerPeriodCap",
    "PricingStrategyKind",
    "ReferenceIncomeCell",
    "ReferenceIncomeSeries",
    "ResolutionError",
    "SettlementWindows",
    "SharingBand",
    "SharingCell",
    "SharingSchedule",
    "ThresholdBasis",
    "ThresholdCheck",
    "ThresholdExit",
    "ThresholdMechanic",
    "ThresholdRequirementResult",
    "ThresholdResult",
    "ThresholdSpec",
    "ThresholdTiming",
    "TransactedLedgerRow",
    "WindDownAssessment",
    "WindDownSpec",
    "build_collections",
    "build_downstream_cash_events",
    "build_netting",
    "build_transacted_ledger",
    "check_compliance",
    "cohort_index",
    "derive_debt_taken",
    "evaluate_threshold",
    "load_company",
    "load_defaults",
    "moic_from_ladder",
    "payback_age",
    "reference_income",
    "resolve_deal_parameters",
    "return_cap",
    "sharing_events_from_schedule",
    "sharing_schedule",
    "winddown_payment",
]
